# Generated by Django 4.1 on 2022-08-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your ame.', max_length=32, verbose_name='Name')),
                ('test_value', models.BooleanField(default=False, help_text='Test model with root option cannot be deleted.', verbose_name='Test value')),
                ('description', models.TextField(help_text='Status of test model object.', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'TestModel',
                'verbose_name_plural': 'TestModels',
            },
        ),
    ]
